// <auto-generated />
using AiSomellierBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiSomellierBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401174139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AiSomellierBackend.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vino rosso toscano robusto",
                            Intensity = "Robusto",
                            Name = "Chianti",
                            Season = "Inverno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vino bianco fresco e leggero",
                            Intensity = "Leggero",
                            Name = "Pinot Grigio",
                            Season = "Estate",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vino rosso piemontese intenso",
                            Intensity = "Robusto",
                            Name = "Barolo",
                            Season = "Autunno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vino bianco marchigiano secco",
                            Intensity = "Medio",
                            Name = "Verdicchio",
                            Season = "Primavera",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vino rosso veneto corposo",
                            Intensity = "Robusto",
                            Name = "Amarone",
                            Season = "Inverno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vino bianco laziale fresco",
                            Intensity = "Leggero",
                            Name = "Frascati",
                            Season = "Estate",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vino rosso versatile italiano",
                            Intensity = "Medio",
                            Name = "Sangiovese",
                            Season = "Autunno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Vino bianco veneto elegante",
                            Intensity = "Medio",
                            Name = "Soave",
                            Season = "Primavera",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vino rosso piemontese acidulo",
                            Intensity = "Medio",
                            Name = "Barbera",
                            Season = "Estate",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Vino spumante frizzante",
                            Intensity = "Leggero",
                            Name = "Prosecco",
                            Season = "Primavera",
                            Type = "Spumante"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Vino rosso siciliano intenso",
                            Intensity = "Robusto",
                            Name = "Nero d'Avola",
                            Season = "Inverno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vino bianco sardo aromatico",
                            Intensity = "Leggero",
                            Name = "Vermentino",
                            Season = "Estate",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Vino rosso campano tannico",
                            Intensity = "Robusto",
                            Name = "Aglianico",
                            Season = "Autunno",
                            Type = "Rosso"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Vino bianco campano fruttato",
                            Intensity = "Medio",
                            Name = "Falanghina",
                            Season = "Primavera",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Vino rosso frizzante emiliano",
                            Intensity = "Leggero",
                            Name = "Lambrusco",
                            Season = "Estate",
                            Type = "Rosso Frizzante"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
